/**
 * 📋 DATA RESMI REKAPITULASI 155 SISWA DARI LAPORAN RESMI PDF
 * SMAN 4 PADANG — GURU MATA PELAJARAN: RINI SYAFITRI
 * Total Siswa: 155 | Rata-Rata: 79.4 | Tertinggi: 100 | Terendah: 0
 * Tingkat Kelulusan (KKM >= 80): 109 dari 155 Siswa (70%)
 */

const OFFICIAL_EXAM_RESULTS = [
  {
    "id": "pdf-rec-1",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "siti khairani",
    "class": "X E 4",
    "score": 100,
    "pointsEarned": 100,
    "totalPoints": 100,
    "correct": 20,
    "total": 20,
    "wrongQuestions": [],
    "time": "08:53 WIB",
    "duration": "2m 44s",
    "date": "28/8/2026",
    "timestamp": 1787881980000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-2",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "nada syifa",
    "class": "X E 4",
    "score": 100,
    "pointsEarned": 100,
    "totalPoints": 100,
    "correct": 20,
    "total": 20,
    "wrongQuestions": [],
    "time": "08:49 WIB",
    "duration": "3m 39s",
    "date": "28/8/2026",
    "timestamp": 1787881740000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-3",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Muhammad kevin riadi",
    "class": "X E 4",
    "score": 100,
    "pointsEarned": 100,
    "totalPoints": 100,
    "correct": 20,
    "total": 20,
    "wrongQuestions": [],
    "time": "08:43 WIB",
    "duration": "5m 20s",
    "date": "28/8/2026",
    "timestamp": 1787881380000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-4",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Athaya humairoh",
    "class": "X E 1",
    "score": 95,
    "pointsEarned": 95,
    "totalPoints": 100,
    "correct": 19,
    "total": 20,
    "wrongQuestions": [
      17
    ],
    "time": "14:36 WIB",
    "duration": "5m 52s",
    "date": "31/8/2026",
    "timestamp": 1788161760000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-5",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Zahrani Sakinah",
    "class": "X E 2",
    "score": 95,
    "pointsEarned": 95,
    "totalPoints": 100,
    "correct": 19,
    "total": 20,
    "wrongQuestions": [
      17
    ],
    "time": "16:29 WIB",
    "duration": "7m 38s",
    "date": "31/8/2026",
    "timestamp": 1788168540000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-6",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "shireen putri ashyla",
    "class": "X E 1",
    "score": 95,
    "pointsEarned": 95,
    "totalPoints": 100,
    "correct": 19,
    "total": 20,
    "wrongQuestions": [
      17
    ],
    "time": "14:35 WIB",
    "duration": "4m 44s",
    "date": "31/8/2026",
    "timestamp": 1788161700000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-7",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Aleesya Nadirah",
    "class": "X E 1",
    "score": 95,
    "pointsEarned": 95,
    "totalPoints": 100,
    "correct": 19,
    "total": 20,
    "wrongQuestions": [
      17
    ],
    "time": "14:44 WIB",
    "duration": "3m 9s",
    "date": "31/8/2026",
    "timestamp": 1788162240000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-8",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Deffid fathahillah sevli",
    "class": "X E 6",
    "score": 95,
    "pointsEarned": 95,
    "totalPoints": 100,
    "correct": 19,
    "total": 20,
    "wrongQuestions": [
      17
    ],
    "time": "11:11 WIB",
    "duration": "4m 45s",
    "date": "19/8/2026",
    "timestamp": 1787112660000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-9",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Kayla Zahira Yusep",
    "class": "X E 4",
    "score": 95,
    "pointsEarned": 95,
    "totalPoints": 100,
    "correct": 19,
    "total": 20,
    "wrongQuestions": [
      17
    ],
    "time": "08:43 WIB",
    "duration": "5m 53s",
    "date": "28/8/2026",
    "timestamp": 1787881380000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-10",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Farhan Putra Alghony",
    "class": "X E 2",
    "score": 95,
    "pointsEarned": 95,
    "totalPoints": 100,
    "correct": 19,
    "total": 20,
    "wrongQuestions": [
      17
    ],
    "time": "16:26 WIB",
    "duration": "4m 57s",
    "date": "31/8/2026",
    "timestamp": 1788168360000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-11",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Daffa Ramadhan",
    "class": "X E 1",
    "score": 95,
    "pointsEarned": 95,
    "totalPoints": 100,
    "correct": 19,
    "total": 20,
    "wrongQuestions": [
      17
    ],
    "time": "14:39 WIB",
    "duration": "7m 11s",
    "date": "31/8/2026",
    "timestamp": 1788161940000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-12",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Rizki Furqan",
    "class": "X E 1",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "14:38 WIB",
    "duration": "7m 36s",
    "date": "31/8/2026",
    "timestamp": 1788161880000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-13",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Ratu Zulaika",
    "class": "X E 1",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "14:39 WIB",
    "duration": "5m 20s",
    "date": "31/8/2026",
    "timestamp": 1788161940000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-14",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "qhairatul hilmi",
    "class": "X E 6",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "11:11 WIB",
    "duration": "4m 13s",
    "date": "19/8/2026",
    "timestamp": 1787112660000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-15",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Efrilna Aulia Putri",
    "class": "X E 2",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "16:32 WIB",
    "duration": "5m 43s",
    "date": "31/8/2026",
    "timestamp": 1788168720000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-16",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Serunj Putri",
    "class": "X E 2",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "16:29 WIB",
    "duration": "5m 45s",
    "date": "31/8/2026",
    "timestamp": 1788168540000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-17",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Vioni Dwi Septia",
    "class": "X E 1",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "14:36 WIB",
    "duration": "4m 57s",
    "date": "31/8/2026",
    "timestamp": 1788161760000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-18",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Faiz Al Putra",
    "class": "X E 4",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "08:50 WIB",
    "duration": "4m 19s",
    "date": "28/8/2026",
    "timestamp": 1787881800000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-19",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Diva Aprilia Putri",
    "class": "X E 6",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "11:16 WIB",
    "duration": "9m 20s",
    "date": "19/8/2026",
    "timestamp": 1787112960000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-20",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "latiffah aryana ardaninggar",
    "class": "X E 6",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "11:16 WIB",
    "duration": "10m 55s",
    "date": "19/8/2026",
    "timestamp": 1787112960000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-21",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Gibran saverio",
    "class": "X E 2",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "16:28 WIB",
    "duration": "6m 51s",
    "date": "31/8/2026",
    "timestamp": 1788168480000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-22",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "nadine puteri donita",
    "class": "X E 2",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "16:27 WIB",
    "duration": "4m 6s",
    "date": "31/8/2026",
    "timestamp": 1788168420000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-23",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Davin Adelio Wahid",
    "class": "X E 4",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "08:55 WIB",
    "duration": "15m 53s",
    "date": "28/8/2026",
    "timestamp": 1787882100000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-24",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Aurora putri islami",
    "class": "X E 4",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "09:01 WIB",
    "duration": "3m 44s",
    "date": "28/8/2026",
    "timestamp": 1787882460000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-25",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Aisyah Padillah",
    "class": "X E 2",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "16:27 WIB",
    "duration": "3m 45s",
    "date": "31/8/2026",
    "timestamp": 1788168420000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-26",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Mahachika Martadani",
    "class": "X E 3",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "08:46 WIB",
    "duration": "3m 56s",
    "date": "20/8/2026",
    "timestamp": 1787190360000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-27",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Naila Fathiyya putri",
    "class": "X E 3",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "08:47 WIB",
    "duration": "5m 26s",
    "date": "20/8/2026",
    "timestamp": 1787190420000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-28",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Naisyila Hermela",
    "class": "X E 3",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "08:48 WIB",
    "duration": "5m 26s",
    "date": "20/8/2026",
    "timestamp": 1787190480000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-29",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Husna Maiza Majid",
    "class": "X E 3",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "08:49 WIB",
    "duration": "6m 29s",
    "date": "20/8/2026",
    "timestamp": 1787190540000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-30",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "ALQI DWI NABILNU",
    "class": "X E 3",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "08:50 WIB",
    "duration": "6m 57s",
    "date": "20/8/2026",
    "timestamp": 1787190600000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-31",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Diva Amanda",
    "class": "X E 3",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "08:51 WIB",
    "duration": "6m 42s",
    "date": "20/8/2026",
    "timestamp": 1787190660000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-32",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "kirana yulia zarni",
    "class": "X E 3",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "08:51 WIB",
    "duration": "5m 15s",
    "date": "20/8/2026",
    "timestamp": 1787190660000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-33",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "NAJLA PUTRI ARUNI",
    "class": "X E 1",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "14:39 WIB",
    "duration": "7m 27s",
    "date": "31/8/2026",
    "timestamp": 1788161940000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-34",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "RACHEL FATHIYA KURNIAWAN",
    "class": "X E 3",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "08:52 WIB",
    "duration": "3m 12s",
    "date": "20/8/2026",
    "timestamp": 1787190720000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-35",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "nurul azdkyah",
    "class": "X E 3",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "08:52 WIB",
    "duration": "8m 7s",
    "date": "20/8/2026",
    "timestamp": 1787190720000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-36",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "QAISYA PUTRI ARIFA",
    "class": "X E 6",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "11:12 WIB",
    "duration": "6m 8s",
    "date": "19/8/2026",
    "timestamp": 1787112720000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-37",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Keysha Afra Mazaya",
    "class": "X E 3",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "08:56 WIB",
    "duration": "3m 58s",
    "date": "20/8/2026",
    "timestamp": 1787190960000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-38",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Roma Putra Wijaya",
    "class": "X E 4",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "08:44 WIB",
    "duration": "4m 56s",
    "date": "28/8/2026",
    "timestamp": 1787881440000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-39",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "DIVA DWI PUTRI",
    "class": "X E 1",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "14:38 WIB",
    "duration": "7m 34s",
    "date": "31/8/2026",
    "timestamp": 1788161880000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-40",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "aira putri ananda",
    "class": "X E 6",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "10:45 WIB",
    "duration": "4m 11s",
    "date": "26/8/2026",
    "timestamp": 1787715900000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-41",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "shadrina kamila",
    "class": "X E 6",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "11:10 WIB",
    "duration": "4m 43s",
    "date": "19/8/2026",
    "timestamp": 1787112600000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-42",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Anggi Aulia",
    "class": "X E 4",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "08:43 WIB",
    "duration": "5m 13s",
    "date": "28/8/2026",
    "timestamp": 1787881380000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-43",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Najla Alya Refandra",
    "class": "X E 4",
    "score": 90,
    "pointsEarned": 90,
    "totalPoints": 100,
    "correct": 18,
    "total": 20,
    "wrongQuestions": [
      17,
      6
    ],
    "time": "08:43 WIB",
    "duration": "5m 7s",
    "date": "28/8/2026",
    "timestamp": 1787881380000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-44",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Yasmin Makhfirah",
    "class": "X E 3",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "08:48 WIB",
    "duration": "5m 53s",
    "date": "20/8/2026",
    "timestamp": 1787190480000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-45",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Kesya Varizka",
    "class": "X E 1",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "14:36 WIB",
    "duration": "5m 42s",
    "date": "31/8/2026",
    "timestamp": 1788161760000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-46",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "reysha Olivia mahendra",
    "class": "X E 6",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "11:12 WIB",
    "duration": "6m 1s",
    "date": "19/8/2026",
    "timestamp": 1787112720000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-47",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Grecylia Aiboy",
    "class": "X E 4",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "08:44 WIB",
    "duration": "6m 39s",
    "date": "28/8/2026",
    "timestamp": 1787881440000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-48",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Nadi",
    "class": "X E 1",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "14:36 WIB",
    "duration": "5m 44s",
    "date": "31/8/2026",
    "timestamp": 1788161760000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-49",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Gevin Artha Alimo",
    "class": "X E 3",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "08:50 WIB",
    "duration": "6m 23s",
    "date": "20/8/2026",
    "timestamp": 1787190600000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-50",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "khansa humaira nasyhwa",
    "class": "X E 2",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "16:28 WIB",
    "duration": "6m 45s",
    "date": "31/8/2026",
    "timestamp": 1788168480000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-51",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Meisya fitri usmy",
    "class": "X E 3",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "08:50 WIB",
    "duration": "7m 42s",
    "date": "20/8/2026",
    "timestamp": 1787190600000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-52",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Monik Assyifa Fauzi",
    "class": "X E 6",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "11:13 WIB",
    "duration": "7m 3s",
    "date": "19/8/2026",
    "timestamp": 1787112780000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-53",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Fakhira Maisa Risani",
    "class": "X E 2",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "16:28 WIB",
    "duration": "6m 6s",
    "date": "31/8/2026",
    "timestamp": 1788168480000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-54",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Clarissa Permata Alika",
    "class": "X E 1",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "14:43 WIB",
    "duration": "4m 31s",
    "date": "31/8/2026",
    "timestamp": 1788162180000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-55",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Fadhlan Assirri",
    "class": "X E 6",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "11:11 WIB",
    "duration": "5m 34s",
    "date": "19/8/2026",
    "timestamp": 1787112660000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-56",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Muhammad Restu Cornella",
    "class": "X E 1",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "14:38 WIB",
    "duration": "7m 0s",
    "date": "31/8/2026",
    "timestamp": 1788161880000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-57",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Naqeeb Parvez Putra Pahlepi",
    "class": "X E 2",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "16:28 WIB",
    "duration": "6m 52s",
    "date": "31/8/2026",
    "timestamp": 1788168480000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-58",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "LABIB ALFARABI LUBIS",
    "class": "X E 2",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "16:36 WIB",
    "duration": "4m 41s",
    "date": "31/8/2026",
    "timestamp": 1788168960000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-59",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "nayla",
    "class": "X E 2",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "16:29 WIB",
    "duration": "5m 58s",
    "date": "31/8/2026",
    "timestamp": 1788168540000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-60",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Muhammad Akhtar Faiz",
    "class": "X E 4",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "08:44 WIB",
    "duration": "5m 58s",
    "date": "28/8/2026",
    "timestamp": 1787881440000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-61",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Fathia Zalia",
    "class": "X E 6",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "11:12 WIB",
    "duration": "6m 1s",
    "date": "19/8/2026",
    "timestamp": 1787112720000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-62",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Faiz Fujianto",
    "class": "X E 1",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "14:33 WIB",
    "duration": "2m 48s",
    "date": "31/8/2026",
    "timestamp": 1788161580000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-63",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Mesy Rosady Saputri",
    "class": "X E 4",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "08:45 WIB",
    "duration": "7m 45s",
    "date": "28/8/2026",
    "timestamp": 1787881500000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-64",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Muhammad fadli Irvandi",
    "class": "X E 1",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "14:39 WIB",
    "duration": "7m 13s",
    "date": "31/8/2026",
    "timestamp": 1788161940000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-65",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "AUDIVA CANIA",
    "class": "X E 6",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "11:12 WIB",
    "duration": "5m 59s",
    "date": "19/8/2026",
    "timestamp": 1787112720000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-66",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Widiya Virgina Sasdi",
    "class": "X E 1",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "14:38 WIB",
    "duration": "6m 25s",
    "date": "31/8/2026",
    "timestamp": 1788161880000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-67",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Gladys Ananta Paula",
    "class": "X E 3",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "08:47 WIB",
    "duration": "5m 38s",
    "date": "20/8/2026",
    "timestamp": 1787190420000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-68",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Bening Khairunnisa Hardiyanto",
    "class": "X E 3",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "08:47 WIB",
    "duration": "5m 39s",
    "date": "20/8/2026",
    "timestamp": 1787190420000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-69",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Abdul Karim Ar Rasyad",
    "class": "X E 3",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "08:48 WIB",
    "duration": "4m 59s",
    "date": "20/8/2026",
    "timestamp": 1787190480000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-70",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "bunga taskia",
    "class": "X E 3",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "08:52 WIB",
    "duration": "7m 14s",
    "date": "20/8/2026",
    "timestamp": 1787190720000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-71",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Adara Premadi",
    "class": "X E 3",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "08:48 WIB",
    "duration": "5m 46s",
    "date": "20/8/2026",
    "timestamp": 1787190480000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-72",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Yoga Pamungkas",
    "class": "X E 2",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "16:26 WIB",
    "duration": "5m 28s",
    "date": "31/8/2026",
    "timestamp": 1788168360000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-73",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "shatara istiriani",
    "class": "X E 3",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "08:48 WIB",
    "duration": "5m 35s",
    "date": "20/8/2026",
    "timestamp": 1787190480000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-74",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "JIBRAN RAMADHAN GANI",
    "class": "X E 3",
    "score": 85,
    "pointsEarned": 85,
    "totalPoints": 100,
    "correct": 17,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13
    ],
    "time": "08:48 WIB",
    "duration": "4m 59s",
    "date": "20/8/2026",
    "timestamp": 1787190480000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-75",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Muhammad.reyvan",
    "class": "X E 2",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "16:36 WIB",
    "duration": "4m 11s",
    "date": "31/8/2026",
    "timestamp": 1788168960000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-76",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Hanny Marcha Prichilla",
    "class": "X E 6",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "11:12 WIB",
    "duration": "5m 12s",
    "date": "19/8/2026",
    "timestamp": 1787112720000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-77",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Revi Wirman Syafitri",
    "class": "X E 6",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "11:11 WIB",
    "duration": "5m 14s",
    "date": "19/8/2026",
    "timestamp": 1787112660000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-78",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "marvita putri",
    "class": "X E 6",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "11:12 WIB",
    "duration": "6m 43s",
    "date": "19/8/2026",
    "timestamp": 1787112720000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-79",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Bima Aribi",
    "class": "X E 6",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "11:12 WIB",
    "duration": "6m 38s",
    "date": "19/8/2026",
    "timestamp": 1787112720000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-80",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "NANDA AFIFAH",
    "class": "X E 6",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "11:13 WIB",
    "duration": "7m 31s",
    "date": "19/8/2026",
    "timestamp": 1787112780000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-81",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "reya najwa",
    "class": "X E 3",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "08:50 WIB",
    "duration": "7m 24s",
    "date": "20/8/2026",
    "timestamp": 1787190600000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-82",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "RAHMAD JAUHAR JAMIL SAPUTRA",
    "class": "X E 3",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "08:50 WIB",
    "duration": "6m 57s",
    "date": "20/8/2026",
    "timestamp": 1787190600000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-83",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Muhammad Rizki",
    "class": "X E 3",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "08:53 WIB",
    "duration": "9m 39s",
    "date": "20/8/2026",
    "timestamp": 1787190780000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-84",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Hazim Ghailan Malazi",
    "class": "X E 3",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "08:55 WIB",
    "duration": "3m 31s",
    "date": "20/8/2026",
    "timestamp": 1787190900000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-85",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Nailah aditha haya p",
    "class": "X E 4",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "08:42 WIB",
    "duration": "4m 44s",
    "date": "28/8/2026",
    "timestamp": 1787881320000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-86",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Nafeeza Aqilah",
    "class": "X E 4",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "08:44 WIB",
    "duration": "6m 16s",
    "date": "28/8/2026",
    "timestamp": 1787881440000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-87",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "olivia darma",
    "class": "X E 4",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "08:44 WIB",
    "duration": "6m 1s",
    "date": "28/8/2026",
    "timestamp": 1787881440000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-88",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Nabila",
    "class": "X E 4",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "08:44 WIB",
    "duration": "6m 16s",
    "date": "28/8/2026",
    "timestamp": 1787881440000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-89",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Biansava",
    "class": "X E 4",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "08:45 WIB",
    "duration": "4m 55s",
    "date": "28/8/2026",
    "timestamp": 1787881500000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-90",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "zivia hutri dewi",
    "class": "X E 4",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "08:44 WIB",
    "duration": "6m 52s",
    "date": "28/8/2026",
    "timestamp": 1787881440000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-91",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Kharisma Ratu Kirana",
    "class": "X E 4",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "08:46 WIB",
    "duration": "7m 52s",
    "date": "28/8/2026",
    "timestamp": 1787881560000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-92",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "nasya soraya efendi",
    "class": "X E 4",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "08:46 WIB",
    "duration": "8m 4s",
    "date": "28/8/2026",
    "timestamp": 1787881560000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-93",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Ajeng Widya Lestari",
    "class": "X E 4",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "08:46 WIB",
    "duration": "8m 32s",
    "date": "28/8/2026",
    "timestamp": 1787881560000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-94",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "FATHAN MAULANA",
    "class": "X E 4",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "08:47 WIB",
    "duration": "9m 7s",
    "date": "28/8/2026",
    "timestamp": 1787881620000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-95",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Rofi Putra Redifra",
    "class": "X E 4",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "08:48 WIB",
    "duration": "9m 50s",
    "date": "28/8/2026",
    "timestamp": 1787881680000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-96",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Farsha khairani",
    "class": "X E 1",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "14:37 WIB",
    "duration": "6m 9s",
    "date": "31/8/2026",
    "timestamp": 1788161820000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-97",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Rahma lutfia putri",
    "class": "X E 1",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "14:37 WIB",
    "duration": "6m 8s",
    "date": "31/8/2026",
    "timestamp": 1788161820000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-98",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Danica Aqila Zafeera",
    "class": "X E 1",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "14:37 WIB",
    "duration": "6m 28s",
    "date": "31/8/2026",
    "timestamp": 1788161820000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-99",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Aditya putra pratama",
    "class": "X E 1",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "14:38 WIB",
    "duration": "7m 56s",
    "date": "31/8/2026",
    "timestamp": 1788161880000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-100",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Aisahputrikarlina yenti",
    "class": "X E 1",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "14:39 WIB",
    "duration": "6m 57s",
    "date": "31/8/2026",
    "timestamp": 1788161940000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-101",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Nadira apri yuliandra",
    "class": "X E 1",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "14:40 WIB",
    "duration": "9m 9s",
    "date": "31/8/2026",
    "timestamp": 1788162000000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-102",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Zifana Letisya",
    "class": "X E 1",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "14:41 WIB",
    "duration": "7m 38s",
    "date": "31/8/2026",
    "timestamp": 1788162060000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-103",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "khansaa alexandra ft",
    "class": "X E 2",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "16:26 WIB",
    "duration": "4m 50s",
    "date": "31/8/2026",
    "timestamp": 1788168360000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-104",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Hulwana Marini",
    "class": "X E 2",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "16:27 WIB",
    "duration": "5m 18s",
    "date": "31/8/2026",
    "timestamp": 1788168420000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-105",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "vanesa aura syifa",
    "class": "X E 2",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "16:27 WIB",
    "duration": "5m 41s",
    "date": "31/8/2026",
    "timestamp": 1788168420000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-106",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "MUGNI ABDUL ROHIM",
    "class": "X E 2",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "16:28 WIB",
    "duration": "6m 57s",
    "date": "31/8/2026",
    "timestamp": 1788168480000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-107",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "keysa putrievi",
    "class": "X E 2",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "16:31 WIB",
    "duration": "4m 46s",
    "date": "31/8/2026",
    "timestamp": 1788168660000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-108",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Salwa Afifah Putri",
    "class": "X E 2",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "16:32 WIB",
    "duration": "7m 58s",
    "date": "31/8/2026",
    "timestamp": 1788168720000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-109",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Muhammad Khairul Azzam",
    "class": "X E 6",
    "score": 80,
    "pointsEarned": 80,
    "totalPoints": 100,
    "correct": 16,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4
    ],
    "time": "11:10 WIB",
    "duration": "4m 41s",
    "date": "19/8/2026",
    "timestamp": 1787112600000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-110",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Muhammad Fadhil Jasriadi",
    "class": "X E 3",
    "score": 75,
    "pointsEarned": 75,
    "totalPoints": 100,
    "correct": 15,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12
    ],
    "time": "08:51 WIB",
    "duration": "7m 54s",
    "date": "20/8/2026",
    "timestamp": 1787190660000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-111",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Pavel abercio persandes",
    "class": "X E 3",
    "score": 75,
    "pointsEarned": 75,
    "totalPoints": 100,
    "correct": 15,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12
    ],
    "time": "08:51 WIB",
    "duration": "6m 29s",
    "date": "20/8/2026",
    "timestamp": 1787190660000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-112",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "lathifah Jumanah Rezki",
    "class": "X E 2",
    "score": 75,
    "pointsEarned": 75,
    "totalPoints": 100,
    "correct": 15,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12
    ],
    "time": "16:28 WIB",
    "duration": "5m 26s",
    "date": "31/8/2026",
    "timestamp": 1788168480000,
    "tabSwitchCount": 1,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-113",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Aimee ishana",
    "class": "X E 6",
    "score": 75,
    "pointsEarned": 75,
    "totalPoints": 100,
    "correct": 15,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12
    ],
    "time": "11:19 WIB",
    "duration": "12m 59s",
    "date": "19/8/2026",
    "timestamp": 1787113140000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-114",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Raudah Permata Sonara",
    "class": "X E 6",
    "score": 75,
    "pointsEarned": 75,
    "totalPoints": 100,
    "correct": 15,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12
    ],
    "time": "10:55 WIB",
    "duration": "6m 50s",
    "date": "26/8/2026",
    "timestamp": 1787716500000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-115",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Rezky dwi putra",
    "class": "X E 4",
    "score": 75,
    "pointsEarned": 75,
    "totalPoints": 100,
    "correct": 15,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12
    ],
    "time": "08:47 WIB",
    "duration": "6m 22s",
    "date": "28/8/2026",
    "timestamp": 1787881620000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-116",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Berlian iberta",
    "class": "X E 3",
    "score": 75,
    "pointsEarned": 75,
    "totalPoints": 100,
    "correct": 15,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12
    ],
    "time": "08:49 WIB",
    "duration": "5m 49s",
    "date": "20/8/2026",
    "timestamp": 1787190540000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-117",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "RIVANO PRATAMA",
    "class": "X E 1",
    "score": 75,
    "pointsEarned": 75,
    "totalPoints": 100,
    "correct": 15,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12
    ],
    "time": "14:46 WIB",
    "duration": "5m 29s",
    "date": "31/8/2026",
    "timestamp": 1788162360000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-118",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Rahima Naura Alfarisi",
    "class": "X E 1",
    "score": 75,
    "pointsEarned": 75,
    "totalPoints": 100,
    "correct": 15,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12
    ],
    "time": "14:39 WIB",
    "duration": "7m 23s",
    "date": "31/8/2026",
    "timestamp": 1788161940000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-119",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Fellydza putri desffendi",
    "class": "X E 1",
    "score": 75,
    "pointsEarned": 75,
    "totalPoints": 100,
    "correct": 15,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12
    ],
    "time": "14:48 WIB",
    "duration": "3m 59s",
    "date": "31/8/2026",
    "timestamp": 1788162480000,
    "tabSwitchCount": 1,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-120",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "muhammad lucky",
    "class": "X E 4",
    "score": 75,
    "pointsEarned": 75,
    "totalPoints": 100,
    "correct": 15,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12
    ],
    "time": "08:47 WIB",
    "duration": "7m 36s",
    "date": "28/8/2026",
    "timestamp": 1787881620000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-121",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Dinda claudia",
    "class": "X E 6",
    "score": 75,
    "pointsEarned": 75,
    "totalPoints": 100,
    "correct": 15,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12
    ],
    "time": "11:18 WIB",
    "duration": "3m 34s",
    "date": "19/8/2026",
    "timestamp": 1787113080000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-122",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Muhammad Vabyan Welfi",
    "class": "X E 1",
    "score": 75,
    "pointsEarned": 75,
    "totalPoints": 100,
    "correct": 15,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12
    ],
    "time": "14:40 WIB",
    "duration": "3m 15s",
    "date": "31/8/2026",
    "timestamp": 1788162000000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-123",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Aurelia Ghasani Fatri",
    "class": "X E 4",
    "score": 75,
    "pointsEarned": 75,
    "totalPoints": 100,
    "correct": 15,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12
    ],
    "time": "08:43 WIB",
    "duration": "4m 50s",
    "date": "28/8/2026",
    "timestamp": 1787881380000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-124",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "NURUL NAJMI NADIRAH",
    "class": "X E 2",
    "score": 75,
    "pointsEarned": 75,
    "totalPoints": 100,
    "correct": 15,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12
    ],
    "time": "16:29 WIB",
    "duration": "7m 37s",
    "date": "31/8/2026",
    "timestamp": 1788168540000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-125",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "RIDHO AHMAD TSAQIF",
    "class": "X E 1",
    "score": 70,
    "pointsEarned": 70,
    "totalPoints": 100,
    "correct": 14,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5
    ],
    "time": "14:39 WIB",
    "duration": "8m 33s",
    "date": "31/8/2026",
    "timestamp": 1788161940000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-126",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Muhammad Rifky",
    "class": "X E 3",
    "score": 70,
    "pointsEarned": 70,
    "totalPoints": 100,
    "correct": 14,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5
    ],
    "time": "08:48 WIB",
    "duration": "4m 55s",
    "date": "20/8/2026",
    "timestamp": 1787190480000,
    "tabSwitchCount": 1,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-127",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Melisa Syahruni",
    "class": "X E 2",
    "score": 70,
    "pointsEarned": 70,
    "totalPoints": 100,
    "correct": 14,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5
    ],
    "time": "16:27 WIB",
    "duration": "6m 4s",
    "date": "31/8/2026",
    "timestamp": 1788168420000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-128",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Natasya Putri",
    "class": "X E 3",
    "score": 70,
    "pointsEarned": 70,
    "totalPoints": 100,
    "correct": 14,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5
    ],
    "time": "08:48 WIB",
    "duration": "5m 38s",
    "date": "20/8/2026",
    "timestamp": 1787190480000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-129",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "nadya fitricya",
    "class": "X E 2",
    "score": 70,
    "pointsEarned": 70,
    "totalPoints": 100,
    "correct": 14,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5
    ],
    "time": "16:30 WIB",
    "duration": "8m 30s",
    "date": "31/8/2026",
    "timestamp": 1788168600000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-130",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "hanifa zahfaleta",
    "class": "X E 4",
    "score": 70,
    "pointsEarned": 70,
    "totalPoints": 100,
    "correct": 14,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5
    ],
    "time": "08:44 WIB",
    "duration": "5m 50s",
    "date": "28/8/2026",
    "timestamp": 1787881440000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-131",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Fathan khalif izzadin",
    "class": "X E 2",
    "score": 70,
    "pointsEarned": 70,
    "totalPoints": 100,
    "correct": 14,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5
    ],
    "time": "16:28 WIB",
    "duration": "7m 26s",
    "date": "31/8/2026",
    "timestamp": 1788168480000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-132",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Khansa Aleta",
    "class": "X E 4",
    "score": 65,
    "pointsEarned": 65,
    "totalPoints": 100,
    "correct": 13,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5,
      18
    ],
    "time": "08:45 WIB",
    "duration": "6m 55s",
    "date": "28/8/2026",
    "timestamp": 1787881500000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-133",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Farel alvedro",
    "class": "X E 1",
    "score": 65,
    "pointsEarned": 65,
    "totalPoints": 100,
    "correct": 13,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5,
      18
    ],
    "time": "14:46 WIB",
    "duration": "7m 11s",
    "date": "31/8/2026",
    "timestamp": 1788162360000,
    "tabSwitchCount": 1,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-134",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Ronaldi saputra",
    "class": "X E 6",
    "score": 65,
    "pointsEarned": 65,
    "totalPoints": 100,
    "correct": 13,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5,
      18
    ],
    "time": "15:18 WIB",
    "duration": "5m 54s",
    "date": "19/8/2026",
    "timestamp": 1787127480000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-135",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Muhammad shidiq al rasyid",
    "class": "X E 6",
    "score": 65,
    "pointsEarned": 65,
    "totalPoints": 100,
    "correct": 13,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5,
      18
    ],
    "time": "11:13 WIB",
    "duration": "7m 15s",
    "date": "19/8/2026",
    "timestamp": 1787112780000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-136",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Nurul Putri",
    "class": "X E 6",
    "score": 65,
    "pointsEarned": 65,
    "totalPoints": 100,
    "correct": 13,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5,
      18
    ],
    "time": "11:14 WIB",
    "duration": "8m 6s",
    "date": "19/8/2026",
    "timestamp": 1787112840000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-137",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Muhammad Arif Irwan",
    "class": "X E 6",
    "score": 65,
    "pointsEarned": 65,
    "totalPoints": 100,
    "correct": 13,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5,
      18
    ],
    "time": "11:13 WIB",
    "duration": "6m 38s",
    "date": "19/8/2026",
    "timestamp": 1787112780000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-138",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Rydho Putra Novinada",
    "class": "X E 3",
    "score": 60,
    "pointsEarned": 60,
    "totalPoints": 100,
    "correct": 12,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5,
      18,
      7
    ],
    "time": "08:51 WIB",
    "duration": "8m 1s",
    "date": "20/8/2026",
    "timestamp": 1787190660000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-139",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Muhammad Rizky as Shidiq",
    "class": "X E 6",
    "score": 60,
    "pointsEarned": 60,
    "totalPoints": 100,
    "correct": 12,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5,
      18,
      7
    ],
    "time": "11:13 WIB",
    "duration": "6m 12s",
    "date": "19/8/2026",
    "timestamp": 1787112780000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-140",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Zhafirah putri faisal",
    "class": "X E 3",
    "score": 60,
    "pointsEarned": 60,
    "totalPoints": 100,
    "correct": 12,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5,
      18,
      7
    ],
    "time": "08:58 WIB",
    "duration": "6m 14s",
    "date": "20/8/2026",
    "timestamp": 1787191080000,
    "tabSwitchCount": 1,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-141",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Karina Ahmad",
    "class": "X E 2",
    "score": 60,
    "pointsEarned": 60,
    "totalPoints": 100,
    "correct": 12,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5,
      18,
      7
    ],
    "time": "16:29 WIB",
    "duration": "7m 10s",
    "date": "31/8/2026",
    "timestamp": 1788168540000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-142",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Havit isra al ashari",
    "class": "X E 2",
    "score": 60,
    "pointsEarned": 60,
    "totalPoints": 100,
    "correct": 12,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5,
      18,
      7
    ],
    "time": "16:32 WIB",
    "duration": "9m 38s",
    "date": "31/8/2026",
    "timestamp": 1788168720000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-143",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Nafla Aprillia nengsih",
    "class": "X E 2",
    "score": 60,
    "pointsEarned": 60,
    "totalPoints": 100,
    "correct": 12,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5,
      18,
      7
    ],
    "time": "16:31 WIB",
    "duration": "3m 22s",
    "date": "31/8/2026",
    "timestamp": 1788168660000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-144",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "PUTRI NAJLA ANDRIKA",
    "class": "X E 2",
    "score": 60,
    "pointsEarned": 60,
    "totalPoints": 100,
    "correct": 12,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5,
      18,
      7
    ],
    "time": "16:30 WIB",
    "duration": "7m 43s",
    "date": "31/8/2026",
    "timestamp": 1788168600000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-145",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "MUHAMMAD HAIKAL",
    "class": "X E 6",
    "score": 55,
    "pointsEarned": 55,
    "totalPoints": 100,
    "correct": 11,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5,
      18,
      7,
      15
    ],
    "time": "11:13 WIB",
    "duration": "8m 3s",
    "date": "19/8/2026",
    "timestamp": 1787112780000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-146",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "MUHAMMAD RAFIF",
    "class": "X E 4",
    "score": 55,
    "pointsEarned": 55,
    "totalPoints": 100,
    "correct": 11,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5,
      18,
      7,
      15
    ],
    "time": "08:47 WIB",
    "duration": "9m 36s",
    "date": "28/8/2026",
    "timestamp": 1787881620000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-147",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Rahmat Farel Erika",
    "class": "X E 2",
    "score": 55,
    "pointsEarned": 55,
    "totalPoints": 100,
    "correct": 11,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5,
      18,
      7,
      15
    ],
    "time": "16:30 WIB",
    "duration": "8m 11s",
    "date": "31/8/2026",
    "timestamp": 1788168600000,
    "tabSwitchCount": 1,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-148",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Fahmi arrahman",
    "class": "X E 1",
    "score": 50,
    "pointsEarned": 50,
    "totalPoints": 100,
    "correct": 10,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5,
      18,
      7,
      15,
      16
    ],
    "time": "14:42 WIB",
    "duration": "11m 8s",
    "date": "31/8/2026",
    "timestamp": 1788162120000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-149",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Arbbi avriel",
    "class": "X E 3",
    "score": 50,
    "pointsEarned": 50,
    "totalPoints": 100,
    "correct": 10,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5,
      18,
      7,
      15,
      16
    ],
    "time": "08:50 WIB",
    "duration": "5m 51s",
    "date": "20/8/2026",
    "timestamp": 1787190600000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-150",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "viola safitri",
    "class": "X E 3",
    "score": 50,
    "pointsEarned": 50,
    "totalPoints": 100,
    "correct": 10,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5,
      18,
      7,
      15,
      16
    ],
    "time": "08:46 WIB",
    "duration": "3m 45s",
    "date": "20/8/2026",
    "timestamp": 1787190360000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-151",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Khalifah cahaya r",
    "class": "X E 1",
    "score": 50,
    "pointsEarned": 50,
    "totalPoints": 100,
    "correct": 10,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5,
      18,
      7,
      15,
      16
    ],
    "time": "14:39 WIB",
    "duration": "8m 26s",
    "date": "31/8/2026",
    "timestamp": 1788161940000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-152",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Salsa resthy ayu",
    "class": "X E 3",
    "score": 50,
    "pointsEarned": 50,
    "totalPoints": 100,
    "correct": 10,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5,
      18,
      7,
      15,
      16
    ],
    "time": "09:02 WIB",
    "duration": "7m 22s",
    "date": "20/8/2026",
    "timestamp": 1787191320000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-153",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "arel pratama",
    "class": "X E 1",
    "score": 45,
    "pointsEarned": 45,
    "totalPoints": 100,
    "correct": 9,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5,
      18,
      7,
      15,
      16,
      2
    ],
    "time": "14:41 WIB",
    "duration": "7m 55s",
    "date": "31/8/2026",
    "timestamp": 1788162060000,
    "tabSwitchCount": 0,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-154",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "frichillia putri ifra",
    "class": "X E 6",
    "score": 40,
    "pointsEarned": 40,
    "totalPoints": 100,
    "correct": 8,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5,
      18,
      7,
      15,
      16,
      2,
      8
    ],
    "time": "11:14 WIB",
    "duration": "7m 30s",
    "date": "19/8/2026",
    "timestamp": 1787112840000,
    "tabSwitchCount": 1,
    "isCheated": false,
    "statusNote": null
  },
  {
    "id": "pdf-rec-155",
    "moduleId": "modul_detektif_fakta",
    "moduleTitle": "Misi Detektif Fakta",
    "name": "Nadzua Dwi atira",
    "class": "X E 6",
    "score": 0,
    "pointsEarned": 0,
    "totalPoints": 100,
    "correct": 0,
    "total": 20,
    "wrongQuestions": [
      17,
      6,
      13,
      4,
      12,
      5,
      18,
      7,
      15,
      16,
      2,
      8,
      10,
      11,
      14,
      3,
      0,
      9,
      19,
      1
    ],
    "time": "11:12 WIB",
    "duration": "4m 37s",
    "date": "19/8/2026",
    "timestamp": 1787112720000,
    "tabSwitchCount": 3,
    "isCheated": true,
    "statusNote": "Diskualifikasi Anti-Cheat (Keluar Tab 3x)"
  }
];

window.OFFICIAL_EXAM_RESULTS = OFFICIAL_EXAM_RESULTS;
